### ISSUE TITLE
breaks on chrome  win 8

### ISSUE THREAD

**Issue by dkaleky** [lorenzos/MooStarRating#3]
See  right column
![moo](https://cloud.githubusercontent.com/assets/4219336/8332260/f52021f4-1a5a-11e5-89ab-b7645a557e97.jpg)

http://screencast.com/t/yj1FsZD9y

**Comment by lorenzos** [comment]
That is an issue that pop out because I'm using hot GitHub linking of JS files in my JSFiddle demo: modern browsers does not executes the JS file because GitHub tells them to enforce strict MIME type checking. I have the same issue on Chromium running on Ubuntu. References:

* https://code.google.com/p/chromium/issues/detail?id=180007
* https://rawgit.com/faq#why
* http://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github

I think I will update all my demos that use JSFiddle using [rawgit.com](https://rawgit.com/). Sure, there should be a lot of demos not working anymore...

**Comment by lorenzos** [comment]
Fixed in 736f77a6
